### ISSUE TITLE
Redis connection issue

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2418]
## Source

CM

## Describe the bug

Some sites sometimes are having Redis connection issues. We can see [one log](https://console.cloud.google.com/logs/query;aroundTime=2023-11-08T13:53:03.502575452Z;cursorTimestamp=2023-11-08T13:47:26.955239889Z;duration=PT1H;pinnedLogId=2023-11-08T13:53:03.502575452Z%2F0mnrm4rya567mv47;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22proudcity-1184%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22proudcity%22%0Aresource.labels.namespace_name%3D%22prod%22%0Alabels.k8s-pod%2Fapp%3D%22rebeccawoodburyca%22%0Alabels.k8s-pod%2Fappid%3D%22rebeccawoodburyca%22%20severity%3E%3DDEFAULT%0Atimestamp%3D%222023-11-08T13:31:32.979069350Z%22%0AinsertId%3D%2291gd9b9w4f56eidk%22?project=proudcity-1184) for it with the `json` output below.

This one seems to apply to the safe redirects plugin.

```json
{
  "textPayload": "[Wed Nov 08 13:31:32.976183 2023] [php:notice] [pid 1704] [client 10.24.17.9:44534] RedisException: read error on connection to rredis:6379 in /app/wordpress/wp-content/object-cache.php:1922\\nStack trace:\\n#0 /app/wordpress/wp-content/object-cache.php(1922): Redis->get('deptofcivicthin...')\\n#1 /app/wordpress/wp-content/object-cache.php(193): WP_Object_Cache->get('_srm_redirects_...', 'transient', false, NULL)\\n#2 /app/wordpress/wp-includes/option.php(906): wp_cache_get('_srm_redirects_...', 'transient')\\n#3 /app/wordpress/wp-content/plugins/safe-redirect-manager/inc/functions.php(19): get_transient('_srm_redirects_...')\\n#4 /app/wordpress/wp-content/plugins/safe-redirect-manager/inc/classes/class-srm-redirect.php(86): srm_get_redirects()\\n#5 /app/wordpress/wp-content/plugins/safe-redirect-manager/inc/classes/class-srm-redirect.php(290): SRM_Redirect->match_redirect('')\\n#6 /app/wordpress/wp-includes/class-wp-hook.php(310): SRM_Redirect->maybe_redirect(Object(WP))\\n#7 /app/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)\\n#8 /app/wordpress/wp-includes/plugin.php(565): WP_Hook->do_action(Array)\\n#9 /app/wordpress/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)\\n#10 /app/wordpress/wp-includes/class-wp.php(779): WP->parse_request('')\\n#11 /app/wordpress/wp-includes/functions.php(1335): WP->main('')\\n#12 /app/wordpress/wp-blog-header.php(16): wp()\\n#13 /app/wordpress/index.php(17): require('/app/wordpress/...')\\n#14 {main}, referer: https://deptofcivicthings.com",
  "insertId": "91gd9b9w4f56eidk",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "proudcity-1184",
      "cluster_name": "proudcity",
      "location": "us-central1-a",
      "container_name": "rebeccawoodburyca",
      "pod_name": "rebeccawoodburyca-7d646f6f7b-fxbcd",
      "namespace_name": "prod"
    }
  },
  "timestamp": "2023-11-08T13:31:32.979069350Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/appid": "rebeccawoodburyca",
    "compute.googleapis.com/resource_name": "gke-proudcity-pool-2-8a9bc504-1r0q",
    "k8s-pod/pod-template-hash": "7d646f6f7b",
    "k8s-pod/app": "rebeccawoodburyca"
  },
  "logName": "projects/proudcity-1184/logs/stderr",
  "receiveTimestamp": "2023-11-08T13:31:53.673505236Z"
}
```

This [one seems](https://console.cloud.google.com/logs/query;aroundTime=2023-11-08T21:29:12.875363977Z;cursorTimestamp=2023-11-08T21:28:23.841803541Z;duration=PT1H;pinnedLogId=2023-11-08T21:29:12.875363977Z%2Fp5y62e0wwtsyx0y4;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22proudcity-1184%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22proudcity%22%0Aresource.labels.namespace_name%3D%22prod%22%0Alabels.k8s-pod%2Fapp%3D%22swansboronc%22%0Alabels.k8s-pod%2Fappid%3D%22swansboronc%22%20severity%3E%3DDEFAULT%0Atimestamp%3D%222023-11-08T21:27:26.575945229Z%22%0AinsertId%3D%220ki32iechdz5i2vo%22?project=proudcity-1184) to be for `wordpress-seo`

```json
{
  "textPayload": "[Wed Nov 08 21:27:24.350905 2023] [php:notice] [pid 6651] [client 10.24.23.181:54390] RedisException: read error on connection to ssredis:6379 in /app/wordpress/wp-content/object-cache.php:1922\\nStack trace:\\n#0 /app/wordpress/wp-content/object-cache.php(1922): Redis->get('swansboro-nc.or...')\\n#1 /app/wordpress/wp-content/object-cache.php(193): WP_Object_Cache->get(10, 'users', false, NULL)\\n#2 /app/wordpress/wp-includes/class-wp-user.php(241): wp_cache_get(10, 'users')\\n#3 /app/wordpress/wp-includes/pluggable.php(102): WP_User::get_data_by('id', 10)\\n#4 /app/wordpress/wp-includes/pluggable.php(84): get_user_by('id', '10')\\n#5 /app/wordpress/wp-includes/class-wp-query.php(4728): get_userdata('10')\\n#6 /app/wordpress/wp-includes/class-wp-query.php(4679): WP_Query->generate_postdata(Object(WP_Post))\\n#7 /app/wordpress/wp-includes/class-wp-query.php(4876): WP_Query->setup_postdata(Object(WP_Post))\\n#8 /app/wordpress/wp-includes/query.php(131): WP_Query->reset_postdata()\\n#9 /app/wordpress/wp-includes/query.php(116): wp_reset_postdata()\\n#10 /app/wordpress/wp-content/plugins/wordpress-seo/src/memoizers/meta-tags-context-memoizer.php(95): wp_reset_query()\\n#11 /app/wordpress/wp-content/plugins/wordpress-seo/src/integrations/front-end/wp-robots-integration.php(87): Yoast\\\\WP\\\\SEO\\\\Memoizers\\\\Meta_Tags_Context_Memoizer->for_current_page()\\n#12 /app/wordpress/wp-content/plugins/wordpress-seo/src/integrations/front-end/wp-robots-integration.php(73): Yoast\\\\WP\\\\SEO\\\\Integrations\\\\Front_End\\\\WP_Robots_Integration->get_robots_value()\\n#13 /app/wordpress/wp-includes/class-wp-hook.php(310): Yoast\\\\WP\\\\SEO\\\\Integrations\\\\Front_End\\\\WP_Robots_Integration->add_robots(Array)\\n#14 /app/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)\\n#15 /app/wordpress/wp-includes/robots-template.php(32): apply_filters('wp_robots', Array)\\n#16 /app/wordpress/wp-includes/class-wp-hook.php(310): wp_robots('')\\n#17 /app/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)\\n#18 /app/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\\n#19 /app/wordpress/wp-includes/general-template.php(3053): do_action('wp_head')\\n#20 /app/wordpress/wp-content/themes/wp-proud-theme/templates/head.php(7): wp_head()\\n#21 /app/wordpress/wp-includes/template.php(787): require('/app/wordpress/...')\\n#22 /app/wordpress/wp-includes/template.php(720): load_template('/app/wordpress/...', false, Array)\\n#23 /app/wordpress/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)\\n#24 /app/wordpress/wp-content/themes/wp-proud-theme/base.php(16): get_template_part('templates/head')\\n#25 /app/wordpress/wp-includes/template-loader.php(106): include('/app/wordpress/...')\\n#26 /app/wordpress/wp-blog-header.php(19): require_once('/app/wordpress/...')\\n#27 /app/wordpress/index.php(17): require('/app/wordpress/...')\\n#28 {main}",
  "insertId": "0ki32iechdz5i2vo",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "swansboronc",
      "cluster_name": "proudcity",
      "location": "us-central1-a",
      "pod_name": "swansboronc-7d876786bb-jxsnn",
      "project_id": "proudcity-1184",
      "namespace_name": "prod"
    }
  },
  "timestamp": "2023-11-08T21:27:26.575945229Z",
  "severity": "ERROR",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-proudcity-pool-2-8a9bc504-gwy2",
    "k8s-pod/appid": "swansboronc",
    "k8s-pod/pod-template-hash": "7d876786bb",
    "k8s-pod/app": "swansboronc"
  },
  "logName": "projects/proudcity-1184/logs/stderr",
  "receiveTimestamp": "2023-11-08T21:27:29.815295859Z"
}
```

Initially that looks similar to [this reported issue with latency](https://github.com/phpredis/phpredis/issues/492). That requires we have `redis-cli` installed, which we don't currently.

- 2023.11.09 - doesn't seem to be latency. I just ran the test above on `loomisca` and the results are: `min: 0, max: 7, avg: 0.68 (2846 samples)` so we have good speed at this moment at least.

**Tasks**
- [x] install Redis CLI
- [x] test latency
  - is the latency high and causing a problem? 

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
We upped connection and read timeout values: https://github.com/proudcity/wp-proudcity/commit/12e90c5d4ba65fb35bd629bd4c94ff349c29bef9

This seems to have reduced how much Redis drops the connection.
